version: '3'
services:
    app:
        image: budgr:latest
        ports:
            - "3000:3000"
        environment:
            MONGO_URI: mongodb://mongodb:27017/budgr
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
