    services:
        app:
            image: budgr:latest
            platform: linux/amd64
            ports:
                - "3000:3001"
            environment:
                OVERRIDE_PORT: 3001
                MONGO_URI: mongodb://mongo:27017/budgr
        mongo:
            image: mongo:latest
            ports:
                - "27017:27017"
            volumes:
                - ./data:/data/db
