name: Build iOS App

on:
    push:
        branches:
            - main
        paths:
            - apps/mobile/**
            - packages/**
    workflow_dispatch: ~

jobs:
    build:
        runs-on: macos-13
        steps:
              - name: Setup repo
                uses: actions/checkout@v4
              - name: Setup Bun
                uses: oven-sh/setup-bun@v1
              - name: Setup Expo
                uses: expo/expo-github-action@v8
                with:
                    expo-version: latest
                    eas-version: latest
                    token: ${{ secrets.EXPO_TOKEN }}

              - uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: 15.2

              - name: Install dependencies
                run: bun install --frozen-lockfile

              - name: Build iOS app (development)
                working-directory: ./apps/mobile
                run: eas build --profile development --platform ios --local --non-interactive --output ${{ github.workspace }}/app-dev.ipa

              - name: Build iOS app (preview)
                working-directory: ./apps/mobile
                run: eas build --profile preview --platform ios --local --non-interactive --output ${{ github.workspace }}/app-preview.ipa

              - name: Upload IPA artifact
                uses: actions/upload-artifact@v4
                with:
                    name: development-build
                    path: ${{ github.workspace }}/app-dev.ipa

              - name: Upload IPA artifact
                uses: actions/upload-artifact@v4
                with:
                    name: preview-build
                    path: ${{ github.workspace }}/app-preview.ipa

              - name: Submit to TestFlight
                run: eas submit -p ios --path=${{ github.workspace }}/app-preview.ipa
